### ISSUE TITLE
Add flagd to devcontainer

### ISSUE THREAD

**Issue by heckelmann** [dynatrace-oss/progressiveDelivery-masterclass#86]

**Comment by agardnerIT** [comment]
the standalone binary or the OFO (which is already on there?)

**Comment by heckelmann** [comment]
> the standalone binary or the OFO (which is already on there?)

The flags binary (https://github.com/open-feature/flagd/releases/tag/core%2Fv0.6.3)
Imho the best way is to add it into the container build here https://github.com/dynatrace-oss/progressiveDelivery-masterclass/blob/main/.devcontainer/Dockerfile#L17
